# Generated by Django 4.2.16 on 2024-10-30 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_representante', models.CharField(max_length=100)),
                ('regional', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=50)),
                ('cnpj_cliente', models.CharField(max_length=50)),
                ('telefone_cliente', models.CharField(max_length=50)),
                ('loja_existe', models.CharField(max_length=50)),
                ('comprou_tubozan', models.CharField(max_length=50)),
                ('conhece_dvg', models.CharField(max_length=50)),
                ('segmento', models.CharField(max_length=50)),
                ('parou_de_comprar', models.CharField(max_length=50)),
                ('tamanho', models.CharField(max_length=50)),
                ('fez_pedido', models.CharField(max_length=50)),
                ('sem_pedido', models.CharField(max_length=50)),
                ('concorrente', models.CharField(max_length=50)),
                ('dif_price', models.CharField(max_length=50)),
                ('obs', models.TextField(blank=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
