# Generated by Django 4.2.16 on 2024-10-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_profile_loginevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
